class_name Bones
enum {
	EYE_LEFT_BONE = 27,
	EYE_RIGHT_BONE = 26,
	
	COLLAR_LEFT_BONE = 58,
	COLLAR_RIGHT_BONE = 37,
	SHOULDER_LEFT_BONE = 59,
	SHOULDER_RIGHT_BONE = 38,
	ELBOW_LEFT_BONE = 60,
	ELBOW_RIGHT_BONE = 39,
	HAND_LEFT_BONE = 61,
	HAND_RIGHT_BONE = 40,
	
	HIPS_BONE = 1,
	PELVIS_BONE = 2,
	ABDOMEN_BONE_1 = 21,
	ABDOMEN_BONE_2 = 22,
	CHEST_BONE = 23,
	NECK_BONE = 24,
	HEAD_BONE = 25,
	
	HIP_LEFT_BONE = 3,
	HIP_RIGHT_BONE = 12,
	KNEE_LEFT_BONE = 4,
	KNEE_RIGHT_BONE = 13,
	ANKLE_LEFT_BONE = 5,
	ANKLE_RIGHT_BONE = 14,
	TOE_LEFT_BONE = 6,
	TOE_RIGHT_BONE = 15,
	
	BREAST_LEFT_BONE = 80,
	BREAST_RIGHT_BONE = 79,
	
	LEFT_INDEX = 66,
	LEFT_MID = 69,
	LEFT_RING = 73,
}
